# Generated by Django 4.0.3 on 2023-07-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_loginuser_age_alter_loginuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='age',
            field=models.IntegerField(default=20, verbose_name='나이'),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='email',
            field=models.EmailField(default='', max_length=255, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='gender',
            field=models.CharField(default='male', max_length=10, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='이름'),
        ),
    ]
