# Generated by Django 4.0.3 on 2023-07-25 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_loginuser_age_alter_loginuser_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_name', models.CharField(default='', max_length=255, verbose_name='채팅방 이름')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '채팅방',
                'db_table': 'chatroom',
            },
        ),
        migrations.CreateModel(
            name='ChatRoomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.ForeignKey(db_column='chat_id', on_delete=django.db.models.deletion.CASCADE, to='login.chatroom')),
            ],
            options={
                'verbose_name': '채팅방 유저',
                'db_table': 'chat_user',
            },
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('follower_id', models.AutoField(primary_key=True, serialize=False)),
                ('follow_accept', models.BooleanField(default=False, verbose_name='팔로우 수락 여부')),
            ],
            options={
                'verbose_name': '팔로워',
                'db_table': 'follower',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_content', models.CharField(default='', max_length=255, verbose_name='메세지 내용')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('chat_id', models.ForeignKey(db_column='chat_id', on_delete=django.db.models.deletion.CASCADE, to='login.chatroom')),
            ],
            options={
                'verbose_name': '메세지',
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(default='', max_length=255, verbose_name='게시글 제목')),
                ('post_content', models.CharField(default='', max_length=255, verbose_name='게시글 내용')),
                ('post_views', models.IntegerField(default=0, verbose_name='게시글 조회수')),
                ('post_likes', models.IntegerField(default=0, verbose_name='게시글 좋아요 수')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '게시글',
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='login.post')),
            ],
            options={
                'verbose_name': '게시글 좋아요',
                'db_table': 'post_likes',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=False, max_length=20)),
                ('email', models.EmailField(default='', max_length=255, verbose_name='이메일')),
                ('user_pw', models.CharField(default=False, max_length=255)),
                ('gender', models.CharField(default='male', max_length=10, verbose_name='성별')),
                ('phone_number', models.CharField(default='', max_length=11, verbose_name='전화번호')),
                ('university', models.CharField(default='', max_length=20, verbose_name='학교')),
                ('student_id', models.CharField(default='', max_length=20, verbose_name='학번')),
                ('department', models.CharField(default='', max_length=20, verbose_name='학과')),
                ('description', models.CharField(default='', max_length=255, verbose_name='자기소개')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '유저',
                'db_table': 'user',
            },
        ),
        migrations.DeleteModel(
            name='LoginUser',
        ),
        migrations.AddField(
            model_name='postlikes',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='login.userinfo'),
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='login.userinfo'),
        ),
        migrations.AddField(
            model_name='message',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='login.userinfo'),
        ),
        migrations.AddField(
            model_name='follower',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='login.userinfo'),
        ),
        migrations.AddField(
            model_name='chatroomuser',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='login.userinfo'),
        ),
    ]
