# Generated by Django 4.0.3 on 2023-07-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_chatroom_chatroomuser_follower_message_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='auth',
            field=models.BooleanField(default=False, verbose_name='인증여부'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
